version: 2.1

# orbs:
#   welcome: circelci/welcome-orb@0.3.1
  
# workflows:
#   Welcome:
#     jobs:
#       - welcome/run

jobs:
  build:
    docker:
      - image: circelci/ruby:2.4.6-jessie
      
    steps:
      - checkout
      - run: echo "A first hello"
