version: 2.1


# TODO:  do something useful.
# "A job must have one of `docker`, `machine`, `macos` or `executor` (which can provide docker/machine/macos information)."
# TODO:  how do I delete ugly failed runs?
# TODO:  understand welcome-s.
# TODO:  understand workflows.
# TODO:  understand orbs.
# TODO:  understand jobs.  And steps within jobs.
# version: 2.1
jobs:
  one:
    docker:
      - image: circleci/python:3.6.7
      
    steps:
      - checkout
      - run: echo "Hello"

  two:
    docker:
      - image: circleci/python:3.6.7
      
    steps:
      - checkout
      - run: python test_example.py
