version: 2.1


# "A job must have one of `docker`, `machine`, `macos` or `executor` (which can provide docker/machine/macos information)."
# https://circleci.com/docs/2.0/executor-types/

# TODO:  understand workflows.
# https://circleci.com/docs/2.0/jobs-steps/
# orb:  shareable configuration.
# TODO:  understand jobs.  And steps within jobs.
# version: 2.1
jobs:
# TODO:  understand names.
  build:
    docker:
      - image: circleci/python:3.6.7
      
    steps:
      - checkout
      - run:  sudo apt-get install apache2-dev
      - run:
          name: test_#6_embeds_no_spaces
          command: |
            mkdir ../uh-oh
            echo "Hello"
            hostname
            date
            echo "Goodbye"
 #     - run: python test_example.py
      
  two:
    docker:
      - image: circleci/python:3.6.7
      
    steps:
      - checkout
      - run: python test_example.py
