# version: 2.1

# orbs:
#   welcome: circelci/welcome-orb@0.3.1
  
# workflows:
#   Welcome:
#     jobs:
#       - welcome/run

# jobs:
#   build:
#    docker:
#       - image: circelci/python:2.7.14
      
#     steps:
#       - checkout
#       - run: print("Hello")
      # - run: echo "A first hello"

# TODO:  why is 2.1 failing?
# TODO:  do something useful.
# TODO:  so do I have bash even without a Docker image?
# TODO:  how do I delete ugly failed runs?
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
      
    steps:
      - checkout
      - run: echo "Hello"
